[package]
name = "mongo_dedupe"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.1.0"
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.31"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
dotenv = 0.15.0